name: combine multipile branches test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: benpiper/architecting-reliability-aws
          path: architecting-reliability-aws
      - uses: actions/checkout@v2
      - run: |
          git config user.name liranpi2
          git remote add mirror https://github.com/benpiper/architecting-reliability-aws
          git fetch --all 
          git merge main
          git push --set-upstream mirror main
