name: combine multipile branches

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: false
      - name: repo-sync 
      - uses: actions/checkout@v2
        with:
          source_repo: "benpiper/architecting-reliability-aws"
          source_branch: "master"
          destination_branch: "main"
          github_token: ${{ secrets.PAT }}
      - run: |
          git config user.name liranpi2
          git remote add mirror https://github.com/benpiper/architecting-reliability-aws.git 
          git fetch --all 
          git merge main
          git push --set-upstream mirror main
