name: GitHub Actions - update submodule
on: [push]
  
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout architecting-reliability-aws
        uses: actions/checkout@v2
        with:
          repository: benpiper/architecting-reliability-aws
          path: architecting-reliability-aws
      
      - name: "git submodule update" 
        run: |
          git config user.name liranpi2
          git pull --recurse-submodules
          git submodule update --remote --recursive
          git commit -am "Auto updated submodule references" && git push || echo "No changes to commit"
